[PASSWORD]
; Session password
cooppassword = coincoin

[GAMEPLAY]
; 0 = Spectate only during boss fights and invasion encounters | 1 = Always spectate other players on death until party wipeout or bonfire rest
always_spectate_on_death = 1

; Spirit summons can aid you in multiplayer.  0=FALSE  1=TRUE
allow_summons = 1

; 0 = Normal | 1 = None | 2 = Display player ping | 3 = Display player soul level | 4 = Display player death count | 5 = Soul level AND ping
overhead_player_display = 0

; 0 = No change | 1 = Will add the player's unique Steam ID to the end of their overhead display. Can be useful for identifying and blocking cheaters
append_steam_id_to_players = 0

; Debuffs (Rot Essence) will be acquired when you die, and will only be cured when you sit at a bonfire.  0=FALSE  1=TRUE
death_debuffs = 0

; Whether to skip the intro logos when booting the game. 0 = FALSE 1 = TRUE
skip_splash_screens = 0

; Game volume before initial save load. 0 = MUTE 10 = MAX
default_boot_master_volume = 5

; Invaders are other players that will join your world uninvited and try to kill you and your party.  0=FALSE  1=TRUE
; Not compatible with ERR.
allow_invaders = 0

[LANGUAGE]
; Leave this blank unless you want to load a custom locale file. The mod will default to your game language.
mod_language_override = 

[SAVE]
; Your save file extension (in the vanilla game this is .sl2). Use any alphanumeric characters (limit = 120)
save_file_extension = err

[SCALING]
; Not compatible with ERR.
enemy_health_scaling = 0
enemy_damage_scaling = 0
enemy_posture_scaling = 0
boss_health_scaling = 0
boss_damage_scaling = 0
boss_posture_scaling = 0

